blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('',views.all_blogs,name='all_blogs'),
    path('<int:blog_id>/',views.detail,name='detail'),
    # path('',views.temp,name='temp'),
    
]

myportfolio/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('blog/', include('blog.urls')),

]
urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from datetime import datetime
from django.db import IntegrityError
# Create your models here.
class Blogs(models.Model):
    title = models.CharField(max_length = 200)
    disription = models.TextField()
    url = models.URLField(blank = True)
    date = models.DateTimeField(default=datetime.now(),blank=True)


    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models
from datetime import datetime
# Create your models here.
class Project(models.Model):
    title = models.CharField(max_length = 100)
    disription = models.CharField(max_length = 500)
    image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank = True)
    date = models.DateTimeField(default=datetime.now(),blank=True)


    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render ,get_object_or_404
from django.http import HttpResponse
from .models import Blogs
# Create your views here.
def all_blogs(request):
    #blog_count = Blogs.objects.count
    blogs = Blogs.objects.order_by('-date')#[:5]#puts limit
    return render(request,'all_blogs.html',{'bb':blogs} )

def detail(request, blog_id):
    blog = get_object_or_404(Blogs, pk=blog_id)
    return render(request, 'detail.html',{'blog':blog})

# def temp(request):
#     return render(request,'temp.html')

portfolio/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Project
# import random 
# Create your views here.
def home(request):
    projects = Project.objects.all()
    return render(request,'home.html',{'projects':projects})

blog/templates/all_blogs.html
{% extends 'base2.html'%}
{% block content %}


<h2>Vanshika Panwar has written {{bb.count}} blog{{bb.count|pluralize}}</h2>

<head>
    <meta charset="UTF-8">
    <title>Blogs</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'cssblog/all_blogs.css'%}">
</head>
{% for b in bb %}
<a href="{% url 'blog:detail' b.id %}"><h2>{{b.title}}</h2></a>

{{b.disription|safe|truncatechars:70}}
<br>
<h5>
{{b.date|date:'M d Y'|upper}}
</h5>
<br>
<!-- <a>url="{{b.url}}" link</a> -->

{%endfor%}
{% endblock %}

blog/templates/base2.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <!-- <title>Hello, world!</title> -->
  </head>
  <body>
    <h1>this coms from base2 which is the base file this all blog</h1>
    {% block content %} {% endblock%}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

blog/templates/detail.html
{% extends 'base2.html'%}
    {% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Details</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'cssblog/all_blogs.css'%}">
</head>
<body>
    
    <h1>{{blog.title}}</h1>
    <h3>--{{blog.date|date:'F jS Y'}}--</h3>
    
    {{blog.disription|safe}}
   
</body>
</html>
{% endblock %}    

portfolio/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'csshome/home.css' %}">
</head>
<body>    
<section id="navbar">
<a href = "{% static 'portfolio/Resume.pdf'%}">Resume</a>
<a href = "{% url 'blog:all_blogs'%}">Blogs</a>
<a href= "https://www.linkedin.com/in/vanshika-panwar-06a737178?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3B3jGOvZhkTGOH1EX5nTXCVA%3D%3D">Linkedin</a>
<h1 id="name" >Vanshika Panwar</h1>  
</section>
<br>
<br>

<div>
    <img src= "{% static 'portfolio/vansh.JPG'%}" height="30%" width="25%">
</div>
<h1 id="Portfolio">Portfolio</h1>
<section id="projects">
{% for p in projects %}
<b id="Pimage">
<img src = "{{p.image.url}}"  height="30%" width="40%" >
</b>
<h2 id="projectname">{{p.title}}</h2>
{{p.disription}}
<br>
{{p.date}}
<br>
<br>
<br>
{% endfor %}
</section>
</body>
</html>